=== HeliosPhoton/Classwork/Lab18/bookExamplewithCSSandValidate/book.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/books.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Books SYSTEM "books.dtd">

    <Books>
    ...
    </Books>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Books (Book)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Book (PublishingInfo|Author|Title)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Author (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PublishingInfo (PublishedYear|PublisherCity|PublisherName)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PublisherName (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PublisherCity (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PublishedYear (#PCDATA)>

=== HeliosPhoton/Classwork/Lab18/bookExamplewithCSSandValidate/book2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE Books PUBLIC '.' 'book.dtd'>
<?xml-stylesheet type="text/css" href="supplements.css"?>

<Books>
	<Book>
	    <Title>A Very Good Book</Title>
	    <Author>Jane Doe</Author>
	    <PublishingInfo>
		<PublisherName>Sams Publishing</PublisherName>
		<PublisherCity>Indianapolis</PublisherCity>
		<PublishedYear>2008</PublishedYear>
	</PublishingInfo>
	</Book>
	<Book>
	    <Title>An Academic Book</Title>
	    <Author>Anne Smith</Author>
	    <PublishingInfo>
		<PublisherName>University of California Press</PublisherName>
		<PublisherCity>Berkeley</PublisherCity>
		<PublishedYear>2008</PublishedYear>
	    </PublishingInfo>
	</Book>
	<Book>
	    <Title>Some Fluff Fiction</Title>
	    <Author>Jimbo Jones</Author>
	    <PublishingInfo>
		<PublisherName>Fluffy Press</PublisherName>
		<PublisherCity>New York</PublisherCity>
		<PublishedYear>2007</PublishedYear>
	    </PublishingInfo>
	</Book>
</Books>
